apiVersion: v1
kind: Service
metadata:
  name: slick-website-service
  labels:
    app: slick-website
spec:
  type: "NodePort"
  ports:
    - port: 80
      targetPort: 80
      name: nginx
  selector:
    app: slick-website
    tier: web
